"""empty message

Revision ID: 0055e75b21f7
Revises: 97cf7335b58e
Create Date: 2020-06-28 02:40:46.803289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0055e75b21f7'
down_revision = '97cf7335b58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('teacherId', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=25), nullable=False),
    sa.Column('assigmentName', sa.String(length=100), nullable=False),
    sa.Column('classfication', sa.String(length=50), nullable=False),
    sa.Column('dueDate', sa.DateTime(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigmentName')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('gradeLevel', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('studentId', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('gradeLevel', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('TeacherId', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('TeacherId'),
    sa.UniqueConstraint('username')
    )
    op.add_column('user', sa.Column('gradeLevel', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('studentId', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['studentId'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'studentId')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'gradeLevel')
    op.drop_table('teacher')
    op.drop_table('students')
    op.drop_table('assigments')
    # ### end Alembic commands ###
