"""empty message

Revision ID: 0ccf8b6e186b
Revises: e35e0443310a
Create Date: 2020-07-22 16:01:02.761442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ccf8b6e186b'
down_revision = 'e35e0443310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('schoolTermId', sa.Integer(), nullable=True))
    op.drop_column('submited_assignments', 'semesterId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('semesterId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('submited_assignments', 'schoolTermId')
    # ### end Alembic commands ###
