"""empty message

Revision ID: 25f675d00526
Revises: 42e2ab1e12f2
Create Date: 2020-07-09 15:47:23.698472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f675d00526'
down_revision = '42e2ab1e12f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.Column('assignmentFile', sa.String(length=80), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('semesterId', sa.Integer(), nullable=True),
    sa.Column('submittable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('school_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=20), nullable=False),
    sa.Column('schoolYear', sa.String(length=20), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter', 'schoolYear')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('gradeLevel', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=False),
    sa.Column('gradeLevel', sa.String(length=80), nullable=False),
    sa.Column('semesterId', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'subjectId', 'semesterId')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('submited_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=False),
    sa.Column('assignmentName', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('assignmentFile', sa.String(length=80), nullable=True),
    sa.Column('submitedDate', sa.DateTime(), nullable=True),
    sa.Column('semesterId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'subjectId', 'assignmentName'),
    sa.UniqueConstraint('submitedDate')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('gradeLevel', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('userName', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('teacher')
    op.drop_table('submited_assignments')
    op.drop_table('subjects')
    op.drop_table('students_grades')
    op.drop_table('students')
    op.drop_table('school_term')
    op.drop_table('assigned_assignments')
    # ### end Alembic commands ###
