"""empty message

Revision ID: 3489dbf21e2f
Revises: 21fe9def6352
Create Date: 2020-07-23 01:46:36.807610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3489dbf21e2f'
down_revision = '21fe9def6352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='assigned_assignments')
    op.create_unique_constraint(None, 'assigned_assignments', ['name', 'schoolTermId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assigned_assignments', type_='unique')
    op.create_index('name', 'assigned_assignments', ['name'], unique=True)
    # ### end Alembic commands ###
