"""empty message

Revision ID: 42e2ab1e12f2
Revises: d16924e8cc5e
Create Date: 2020-07-09 14:21:28.046670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42e2ab1e12f2'
down_revision = 'd16924e8cc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('subject', sa.String(length=30), nullable=False))
    op.drop_index('math', table_name='subjects')
    op.drop_index('music', table_name='subjects')
    op.drop_index('physicalEducation', table_name='subjects')
    op.drop_index('reading', table_name='subjects')
    op.drop_index('science', table_name='subjects')
    op.drop_index('socialStudies', table_name='subjects')
    op.create_unique_constraint(None, 'subjects', ['subject'])
    op.drop_column('subjects', 'reading')
    op.drop_column('subjects', 'socialStudies')
    op.drop_column('subjects', 'music')
    op.drop_column('subjects', 'science')
    op.drop_column('subjects', 'math')
    op.drop_column('subjects', 'physicalEducation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('physicalEducation', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('math', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('science', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('music', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('socialStudies', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('reading', mysql.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'subjects', type_='unique')
    op.create_index('socialStudies', 'subjects', ['socialStudies'], unique=True)
    op.create_index('science', 'subjects', ['science'], unique=True)
    op.create_index('reading', 'subjects', ['reading'], unique=True)
    op.create_index('physicalEducation', 'subjects', ['physicalEducation'], unique=True)
    op.create_index('music', 'subjects', ['music'], unique=True)
    op.create_index('math', 'subjects', ['math'], unique=True)
    op.drop_column('subjects', 'subject')
    # ### end Alembic commands ###
