"""empty message

Revision ID: 5c33226e510f
Revises: 6cdd4fa2e8d7
Create Date: 2020-07-06 14:26:23.502449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c33226e510f'
down_revision = '6cdd4fa2e8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_assigments', 'assigmentFile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assigments', sa.Column('assigmentFile', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
