"""empty message

Revision ID: 5c8a5dc75202
Revises: c0dc63dac741
Create Date: 2020-07-23 13:55:19.789275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c8a5dc75202'
down_revision = 'c0dc63dac741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_class_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('subjectId', sa.Integer(), nullable=False),
    sa.Column('schoolTermId', sa.Integer(), nullable=False),
    sa.Column('gradeAvg', sa.Integer(), nullable=False),
    sa.Column('gradeLetter', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'subjectId', 'schoolTermId')
    )
    op.drop_index('studentId', table_name='students_grades')
    op.drop_table('students_grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_grades',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('studentId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subjectId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schoolTermId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gradeAvg', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gradeLetter', mysql.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('studentId', 'students_grades', ['studentId', 'subjectId', 'schoolTermId'], unique=True)
    op.drop_table('students_class_grades')
    # ### end Alembic commands ###
