"""empty message

Revision ID: 6cdd4fa2e8d7
Revises: f5401ae5033f
Create Date: 2020-07-06 14:25:31.336547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdd4fa2e8d7'
down_revision = 'f5401ae5033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('math', sa.String(length=30), nullable=True),
    sa.Column('english', sa.String(length=30), nullable=True),
    sa.Column('art', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('art'),
    sa.UniqueConstraint('english'),
    sa.UniqueConstraint('math')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
