"""empty message

Revision ID: 7ff37bb2fe5e
Revises: f60d63b471d5
Create Date: 2020-07-09 13:31:50.034106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ff37bb2fe5e'
down_revision = 'f60d63b471d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('subjectId', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.Column('assignmentFile', sa.String(length=80), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('semesterId', sa.Integer(), nullable=True),
    sa.Column('submittable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('school_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=20), nullable=False),
    sa.Column('schoolYear', sa.String(length=20), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter', 'schoolYear')
    )
    op.drop_index('name', table_name='assigned_assigments')
    op.drop_table('assigned_assigments')
    op.drop_index('quarter', table_name='semester')
    op.drop_table('semester')
    op.add_column('students_grades', sa.Column('subjectId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'students_grades', ['studentId', 'subjectId', 'semesterId'])
    op.drop_column('students_grades', 'subject')
    op.add_column('submited_assignments', sa.Column('assignmentFile', sa.String(length=80), nullable=True))
    op.add_column('submited_assignments', sa.Column('subjectId', sa.Integer(), nullable=False))
    op.drop_index('studentId', table_name='submited_assignments')
    op.create_unique_constraint(None, 'submited_assignments', ['studentId', 'subjectId', 'assignmentName'])
    op.drop_column('submited_assignments', 'assigmentFile')
    op.drop_column('submited_assignments', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('submited_assignments', sa.Column('assigmentFile', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'submited_assignments', type_='unique')
    op.create_index('studentId', 'submited_assignments', ['studentId', 'subject', 'assignmentName'], unique=True)
    op.drop_column('submited_assignments', 'subjectId')
    op.drop_column('submited_assignments', 'assignmentFile')
    op.add_column('students_grades', sa.Column('subject', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'students_grades', type_='unique')
    op.drop_column('students_grades', 'subjectId')
    op.create_table('semester',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quarter', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('schoolYear', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`current` in (0,1))', name='semester_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('quarter', 'semester', ['quarter', 'schoolYear'], unique=True)
    op.create_table('assigned_assigments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('dueDate', mysql.DATETIME(), nullable=True),
    sa.Column('semesterId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('assigmentFile', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('submittable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('subjectId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`submittable` in (0,1))', name='assigned_assigments_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'assigned_assigments', ['name'], unique=True)
    op.drop_table('school_term')
    op.drop_table('assigned_assignments')
    # ### end Alembic commands ###
