"""empty message

Revision ID: 87aa22d159c7
Revises: 5c33226e510f
Create Date: 2020-07-06 14:26:39.504635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aa22d159c7'
down_revision = '5c33226e510f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assigments', sa.Column('assigmentFile', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_assigments', 'assigmentFile')
    # ### end Alembic commands ###
