"""empty message

Revision ID: 8911e5c960dc
Revises: 87aa22d159c7
Create Date: 2020-07-08 16:56:42.288232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8911e5c960dc'
down_revision = '87aa22d159c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'semester', ['quarter', 'schoolYear'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semester', type_='unique')
    # ### end Alembic commands ###
