"""empty message

Revision ID: a9ab650a82af
Revises: f7df2d27101f
Create Date: 2020-07-09 02:58:16.089715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9ab650a82af'
down_revision = 'f7df2d27101f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assigments', sa.Column('subjectId', sa.Integer(), nullable=True))
    op.drop_column('assigned_assigments', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assigments', sa.Column('subject', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('assigned_assigments', 'subjectId')
    # ### end Alembic commands ###
