"""empty message

Revision ID: aa6f8719e837
Revises: 63c637ead134
Create Date: 2020-07-24 01:58:22.884481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa6f8719e837'
down_revision = '63c637ead134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_class_grades', 'gradeAvg',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('students_class_grades', 'gradeLetter',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_class_grades', 'gradeLetter',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('students_class_grades', 'gradeAvg',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
