"""empty message

Revision ID: b3c9fcebee09
Revises: c6f43e030700
Create Date: 2020-07-08 21:32:16.162133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c9fcebee09'
down_revision = 'c6f43e030700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submited_assigments', ['submitedDate'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submited_assigments', type_='unique')
    # ### end Alembic commands ###
