"""empty message

Revision ID: bcd28c74d56f
Revises: f4cc4d4f8448
Create Date: 2020-07-08 21:06:59.241099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd28c74d56f'
down_revision = 'f4cc4d4f8448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('music', sa.String(length=30), nullable=True))
    op.add_column('subjects', sa.Column('physicalEducation', sa.String(length=30), nullable=True))
    op.add_column('subjects', sa.Column('reading', sa.String(length=30), nullable=True))
    op.add_column('subjects', sa.Column('science', sa.String(length=30), nullable=True))
    op.add_column('subjects', sa.Column('socialStudies', sa.String(length=30), nullable=True))
    op.drop_index('art', table_name='subjects')
    op.drop_index('english', table_name='subjects')
    op.create_unique_constraint(None, 'subjects', ['music'])
    op.create_unique_constraint(None, 'subjects', ['physicalEducation'])
    op.create_unique_constraint(None, 'subjects', ['science'])
    op.create_unique_constraint(None, 'subjects', ['socialStudies'])
    op.create_unique_constraint(None, 'subjects', ['reading'])
    op.drop_column('subjects', 'art')
    op.drop_column('subjects', 'english')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('english', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('subjects', sa.Column('art', mysql.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.create_index('english', 'subjects', ['english'], unique=True)
    op.create_index('art', 'subjects', ['art'], unique=True)
    op.drop_column('subjects', 'socialStudies')
    op.drop_column('subjects', 'science')
    op.drop_column('subjects', 'reading')
    op.drop_column('subjects', 'physicalEducation')
    op.drop_column('subjects', 'music')
    # ### end Alembic commands ###
