"""empty message

Revision ID: c0dc63dac741
Revises: 1cec5e4d48ba
Create Date: 2020-07-23 13:53:23.295054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0dc63dac741'
down_revision = '1cec5e4d48ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_grades', 'gradeLevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_grades', sa.Column('gradeLevel', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
