"""empty message

Revision ID: ce5d2c846946
Revises: 06a0dae9a605
Create Date: 2020-07-13 13:25:22.518036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce5d2c846946'
down_revision = '06a0dae9a605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assignments', sa.Column('schoolTermId', sa.Integer(), nullable=False))
    op.drop_column('assigned_assignments', 'semesterId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assignments', sa.Column('semesterId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('assigned_assignments', 'schoolTermId')
    # ### end Alembic commands ###
