"""empty message

Revision ID: cfea75aa77b0
Revises: d1cf32b5f0af
Create Date: 2020-08-11 03:18:22.172485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfea75aa77b0'
down_revision = 'd1cf32b5f0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assigned_assignments', ['assignmentName', 'schoolTermId'])
    op.drop_column('assigned_assignments', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assignments', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'assigned_assignments', type_='unique')
    # ### end Alembic commands ###
