"""empty message

Revision ID: d16924e8cc5e
Revises: 7ff37bb2fe5e
Create Date: 2020-07-09 13:33:56.043731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd16924e8cc5e'
down_revision = '7ff37bb2fe5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students_grades', ['studentId', 'subjectId', 'semesterId'])
    op.drop_column('students_grades', 'subject')
    op.add_column('submited_assignments', sa.Column('assignmentFile', sa.String(length=80), nullable=True))
    op.add_column('submited_assignments', sa.Column('subjectId', sa.Integer(), nullable=False))
    op.drop_index('studentId', table_name='submited_assignments')
    op.create_unique_constraint(None, 'submited_assignments', ['studentId', 'subjectId', 'assignmentName'])
    op.drop_column('submited_assignments', 'subject')
    op.drop_column('submited_assignments', 'assigmentFile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('assigmentFile', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('submited_assignments', sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'submited_assignments', type_='unique')
    op.create_index('studentId', 'submited_assignments', ['studentId', 'subject', 'assignmentName'], unique=True)
    op.drop_column('submited_assignments', 'subjectId')
    op.drop_column('submited_assignments', 'assignmentFile')
    op.add_column('students_grades', sa.Column('subject', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'students_grades', type_='unique')
    # ### end Alembic commands ###
