"""empty message

Revision ID: d2d6517165b9
Revises: cfea75aa77b0
Create Date: 2020-09-07 00:49:13.808377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2d6517165b9'
down_revision = 'cfea75aa77b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'gradeLevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('gradeLevel', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
