"""empty message

Revision ID: f436db3360b2
Revises: c79431433678
Create Date: 2020-08-11 03:03:20.257577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f436db3360b2'
down_revision = 'c79431433678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('submittedFile', sa.String(length=80), nullable=True))
    op.drop_column('submited_assignments', 'assignmentFile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submited_assignments', sa.Column('assignmentFile', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('submited_assignments', 'submittedFile')
    # ### end Alembic commands ###
