"""empty message

Revision ID: f4cc4d4f8448
Revises: 8911e5c960dc
Create Date: 2020-07-08 17:21:57.899363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cc4d4f8448'
down_revision = '8911e5c960dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester', sa.Column('current', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semester', 'current')
    # ### end Alembic commands ###
