"""empty message

Revision ID: f60d63b471d5
Revises: f06537f99cd4
Create Date: 2020-07-09 13:15:00.132776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f60d63b471d5'
down_revision = 'f06537f99cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submited_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('assignmentName', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('assigmentFile', sa.String(length=80), nullable=True),
    sa.Column('submitedDate', sa.DateTime(), nullable=True),
    sa.Column('semesterId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentId', 'subject', 'assignmentName'),
    sa.UniqueConstraint('submitedDate')
    )
    op.drop_index('submitedDate', table_name='submited_assigments')
    op.drop_table('submited_assigments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submited_assigments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('studentId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('assigmentName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('grade', mysql.FLOAT(), nullable=True),
    sa.Column('semesterId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigmentFile', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('submitedDate', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('assignmentName', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('submitedDate', 'submited_assigments', ['submitedDate'], unique=True)
    op.drop_table('submited_assignments')
    # ### end Alembic commands ###
