"""empty message

Revision ID: f7df2d27101f
Revises: b3c9fcebee09
Create Date: 2020-07-09 02:46:15.845147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7df2d27101f'
down_revision = 'b3c9fcebee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_assigments', sa.Column('submittable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_assigments', 'submittable')
    # ### end Alembic commands ###
